password = '12345678'
user1 = User.create(name: 'Test member', email: 'test@member1.com', password: password)
user2 = User.create(name: 'Test member', email: 'test@member2.com', password: password)
user3 = User.create(name: 'Test member', email: 'test@member3.com', password: password)
user4 = User.create(name: 'Test member', email: 'test@member4.com', password: password)
user5 = User.create(name: 'Test member', email: 'test@member5.com', password: password)
user6 = User.create(name: 'Test overdue', email: 'test@memberoverdue.com', password: password, api_token: "654321")
user7 = User.create(name: 'Test Librarian', email: 'test@librarian.com', password: password, role: "librarian", api_token: "123456")

genres=['Cience Fiction', 'Romance']
title = "The Hitchhiker's Guide to the Galaxy"
book1 = Book.create(title: title+" 1", author: "Douglas Adams", genre: genres, isbn: "12345671", total_copies: 10)
book2 = Book.create(title: title+" 2", author: "Douglas Adams", genre: genres, isbn: "12345672", total_copies: 10)
book3 = Book.create(title: title+" 3", author: "Douglas Adams", genre: genres, isbn: "12345673", total_copies: 10)
book4 = Book.create(title: title+" 4", author: "Douglas Adams", genre: genres, isbn: "12345674", total_copies: 10)
book5 = Book.create(title: title+" 5", author: "Douglas Adams", genre: genres, isbn: "12345675", total_copies: 10)
book6 = Book.create(title: title+" 6", author: "Douglas Adams", genre: genres, isbn: "12345676", total_copies: 10)
book7 = Book.create(title: title+" 7", author: "Douglas Adams", genre: genres, isbn: "12345677", total_copies: 10)
book8 = Book.create(title: title+" 8", author: "Douglas Adams", genre: genres, isbn: "12345678", total_copies: 10)

BorrowedBook.create(user_id: user1.id, book_id: book1.id, due_date: Date.today + 1.day)
BorrowedBook.create(user_id: user1.id, book_id: book2.id, due_date: Date.today + 2.days)
BorrowedBook.create(user_id: user1.id, book_id: book3.id, due_date: Date.today + 14.days)
BorrowedBook.create(user_id: user2.id, book_id: book1.id, due_date: Date.today)
BorrowedBook.create(user_id: user2.id, book_id: book3.id, due_date: Date.today)
BorrowedBook.create(user_id: user2.id, book_id: book2.id, due_date: Date.today + 2.days)
BorrowedBook.create(user_id: user3.id, book_id: book1.id, due_date: Date.today + 2.days)
BorrowedBook.create(user_id: user3.id, book_id: book4.id, due_date: Date.today + 2.days)
BorrowedBook.create(user_id: user3.id, book_id: book3.id, due_date: Date.today)
BorrowedBook.create(user_id: user3.id, book_id: book2.id, due_date: Date.today)
BorrowedBook.create(user_id: user4.id, book_id: book5.id, due_date: Date.today)
BorrowedBook.create(user_id: user4.id, book_id: book6.id, due_date: Date.today + 2.days)
BorrowedBook.create(user_id: user6.id, book_id: book1.id, due_date: Date.today + 2.days)
BorrowedBook.create(user_id: user6.id, book_id: book2.id, due_date: Date.today)
BorrowedBook.create(user_id: user6.id, book_id: book3.id, due_date: Date.today, status: "returned")
BorrowedBook.create(user_id: user6.id, book_id: book4.id, due_date: Date.today + 2.days)
BorrowedBook.create(user_id: user6.id, book_id: book5.id, due_date: Date.today + 2.days)
BorrowedBook.create(user_id: user6.id, book_id: book6.id, due_date: Date.today + 2.days)
BorrowedBook.create(user_id: user6.id, book_id: book7.id, due_date: Date.today)
BorrowedBook.create(user_id: user6.id, book_id: book8.id, due_date: Date.today - 7.days)
BorrowedBook.create(user_id: user6.id, book_id: book3.id, due_date: Date.today - 2.days)